### PR TITLE
update zlib dependency to 0.1.7

### PR DESCRIPTION
**Pull request by andrewrk**
also removed dead dependency from package.json

### CODE REVIEW

**Comment by brianloveswords** [comment]
Sorry for the long delay on this! GitHub didn't have me as "watching" the repo for some reason so I wasn't getting any notifications for it.

This is actually the opposite of what I want: I want to be using `tape` and not `tap` for testing. So `tap` should be removed and the test script should be changed to use `tape`. They are functionally identical on the command line, but `tape` also works in the browser so it can be used with [testling](https://ci.testling.com/)

**Comment by andrewrk** [comment]
Cool do you want to pull the request anyway since it does not change testing behavior at all and updates the zlib dependency? You can always fix your testing setup the way you want later.

**Comment by brianloveswords** [comment]
AH HA, I didn't notice the supressed diff – at first glance it seemed like just a package.json change. 

The easiest thing would be if you committed another request to reverse the package.json change (github will automatically update this PR if your push it to you `master` branch). If you don't wanna do that, I can merge this and then make the change myself.

**Comment by andrewrk** [comment]
how's that?

**Comment by brianloveswords** [comment]
Awesome, thank you!! :pizza:

**Comment by andrewrk** [comment]
oh and please make sure to remove tape from dependencies. (put it in devDependencies) nobody wants the "tape" code running in their browser in production

**Comment by brianloveswords** [comment]
v0.0.3 published on npm

**Pull request merged**
